#!/bin/bash

if [ $1 = "1" ]; then 
	echo -e "Разработчик скрипта - Коновальчук Денис ИТИ-11"
fi

if [ $1 = "2" ]; then 
	echo -e "252"
fi

if [ $1 = "3" ]; then
	zip -r archive.zip *.$2	
fi

s=0

if [ $1 = "4" ]; then
	for file in `find "$2/" -type f`
	do
	if [ ${#file} > s ];then
		s=${#file}
		name=$file
	fi
	done
fi

echo $name
